name: "Grammar Checker Action"
description: "Проверяет орфографию в указанных файлах с помощью Яндекс.Speller API"
inputs:
  files:
    description: "Список файлов для проверки, разделённых пробелами"
    required: true
    type: string
runs:
  using: "composite"
  steps:
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        pip install -r requirements.txt

    - name: Run Grammar Checker Script
      run: |
        python main.py ${{ inputs.files }}
      shell: bash